// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknEF3vM5zIKLgvjIkI4Hvgc79etxl7Jw',
    appId: '1:579179961951:web:0ef57b6e7e1a93025ec5ea',
    messagingSenderId: '579179961951',
    projectId: 'tmef-e05a2',
    authDomain: 'tmef-e05a2.firebaseapp.com',
    storageBucket: 'tmef-e05a2.appspot.com',
    measurementId: 'G-VL9KFFM65C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlodpXLbXwuSkVqNHnHHzm0brRR4Wh2c',
    appId: '1:579179961951:android:0a5ff5c5b0d510315ec5ea',
    messagingSenderId: '579179961951',
    projectId: 'tmef-e05a2',
    storageBucket: 'tmef-e05a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNs62n37MNruw4AghdXftmmx2kYBnqj8',
    appId: '1:579179961951:ios:7ed67c826b405cce5ec5ea',
    messagingSenderId: '579179961951',
    projectId: 'tmef-e05a2',
    storageBucket: 'tmef-e05a2.appspot.com',
    iosClientId: '579179961951-p8dt5cdi58pjqkrc53fpglv87iau50dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNs62n37MNruw4AghdXftmmx2kYBnqj8',
    appId: '1:579179961951:ios:f65cdf8554f3134a5ec5ea',
    messagingSenderId: '579179961951',
    projectId: 'tmef-e05a2',
    storageBucket: 'tmef-e05a2.appspot.com',
    iosClientId: '579179961951-ig2ht0k9s31j2v77o0skhcbecgtqnlu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tme.RunnerTests',
  );
}
